config/routes.rb
SongNinja::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"

  devise_for :users

  resources :users do
    resources :bands do
      resources :albums do
        resources :songs
      end
    end

    resources :song_creation_services
    resources :album_creation_services
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :songs, dependent: :destroy
  belongs_to :band, touch: true
end

app/models/album_sweeper.rb
class AlbumSweeper < ActionController::Caching::Sweeper

  def after_create
    expire_cache
  end

  def after_update
    expire_cache
  end

  def after_destroy
    expire_cache
  end

  private

  def expire_cache
    expire_page(controller: 'albums', action: 'show')
    expire_page(controller: 'bands', action: 'index')
  end
end

app/models/band.rb
class Band < ActiveRecord::Base
  has_many :songs, dependent: :destroy
  has_many :albums, dependent: :destroy
end

app/models/permitted_parameters.rb
class PermittedParameters
  include Virtus

  attribute :parameters, String
  attribute :user, String

  def current_model(model)
    parameters.require(model).permit!
  end

  def usr
    if user.has_role? :admin
      parameters.require(:user).permit!
    else
      parameters.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation,
        :remember_me
      )
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  scopify
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :album, touch: true
  belongs_to :band, touch: true
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/album_creation_services_controller.rb
class AlbumCreationServicesController < ApplicationController

  def new
    @album_service = AlbumCreationService.new
  end

  def create
    @album_service = AlbumCreationService.new(parameters)

    if @album_service.save
      redirect_to [ current_user, @album_service.band, @album_service.album ]
    else
      redirect_to root_url, alert: @album_service.errors.full_messages.join(", ")
    end
  end

  private

  def parameters
    permitted_params.current_model(:album_creation_service)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  inherit_resources

  def edit
    edit! do
      @band = @album.band
    end
  end

  def update
    @album = Album.find(params[:id])
    @album.update_attributes(album_params)
    super
  end

  private

  def album_params
    permitted_params.current_model(:album)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

  private

  def permitted_params
    @permitted_paramaters ||= PermittedParameters.new(parameters: params, user: current_user)
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  inherit_resources

  respond_to :html, :json, :js

  def index
    index! do
      @bands = Band.order(:name)
    end
  end

  def update
    @band = Band.find(params[:id])
    @band.update_attributes(band_params)
    super
  end

  private

  def band_params
    permitted_params.current_model(:band)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @song_service = SongCreationService.new
    @album_service = AlbumCreationService.new
  end
end

app/controllers/song_creation_services_controller.rb
class SongCreationServicesController < ApplicationController
  respond_to :html, :js

  def new
    @song_service = SongCreationService.new
  end

  def create
    @song_service = SongCreationService.new(parameters)

    if @song_service.save
      redirect_to [ current_user, @song_service.band, @song_service.album, @song_service.song ]
    else
      redirect_to root_url, alert: @song_service.errors.full_messages.join(", ")
    end
  end

  private

  def parameters
    permitted_params.current_model(:song_creation_service)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  inherit_resources

  respond_to :html, :json, :js

  def show
    show! do
      @album = Album.find(params[:album_id])
    end
  end

  def update
    @song = Song.find(params[:id])
    @song.update_attributes(song_params)

    update! do |success, failure|
      success.html { redirect_to [current_user, @song.band, @song] }
      failure.html { redirect_to [current_user, @song.band, @song] }
    end
  end

  private

  def song_params
    permitted_params.current_model(:song)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(permitted_params.usr)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/album_creation_services/_form.html.haml
= simple_form_for [ current_user, @album_service ], html: { class: 'form-inline' } do |f|
  = f.error_notification message: flash[:alert]

  .controls.control-row
    = f.input_field :band,  input_html: { class: 'span3' }, placeholder: 'Band Name'
    = f.input_field :album, input_html: { class: 'span3' }, placeholder: 'Record Title'

  .controls
    = f.submit 'Create Album', class: 'add-song btn btn-success', disable_with: 'Creating...'

app/views/albums/_form.html.haml
= simple_form_for [ current_user, @band, @album ] do |f|
  = f.error_notification

  = f.input :title

  = f.submit 'Update Album', class: 'btn btn-success'
  = link_to 'Cancel', user_bands_path(current_user), class: 'btn btn-inverse'

app/views/albums/edit.html.haml
%h3= @album.title

.span3
  = render 'form'

.span5
  %table.table.table-bordered.song-table
    %tr
      %th Song Title

    - @album.songs.each do |song|
      %tr
        %td= link_to song.title, [ current_user, @album.band, @album, song ]
        %td= link_to 'Remove Song', [ current_user, @album.band, @album, song ], method: :delete, class: 'btn-small btn-danger'

app/views/albums/show.html.haml
= cache @album do
  %h3.album-title= @album.title

  .span2
    %ul.thumbnails
      %li
        = image_tag @album.image

  .span3
    .track-list
      %ul
        - @album.songs.each do |song|
          %li= link_to song.title, [ current_user, @album.band, @album, song ]

app/views/bands/_form.html.haml
= simple_form_for [ current_user, @band ] do |f|
  = f.error_notification

  .form-inputs
    = f.input :name

  .form-actions
    = f.button :submit, class: 'btn btn-success'
    = link_to 'Cancel', user_bands_path(current_user), class: 'btn btn-inverse'

app/views/bands/edit.html.haml
%h3 Edit band information

= render 'form'

app/views/bands/index.html.haml
%h3 The bands you have selected, Ninja-san

= cache @bands do
  .span3
    %ul.nav.nav-list
      %li.nav-header Bands
      - @bands.each_with_index do |band, index|
        - active = index == 0 ? 'active' : ''
        %li{id: band.id, class: active }= link_to band.name, '#'


  .span5
    - @bands.each_with_index do |band, index|
      - visibility = index == 0 ? 'block' : 'none'
      %table{ class: 'table table-bordered', id: dom_id(band), style: "display: #{visibility}"}
        %tr
          %th Record Title

        - band.albums.each do |album|
          %tr
            %td= link_to album.title, [ current_user, band, album ]
            %td= link_to 'Remove Album', [ current_user, band, album ], method: :delete, class: 'btn-small btn-danger'
            %td= link_to 'Edit Album', [ :edit, current_user, band, album ], class: 'btn-small btn-info'

      .btn-group{ id: dom_id(band), style: "display: #{visibility}" }
        = link_to 'Edit Band', edit_user_band_path(current_user, band.id), class: 'btn'
        = link_to 'Remove Band', user_band_path(current_user,band), method: :delete, confirm: 'Warning: Permanantly Removes Band', class: 'btn'

app/views/home/_creation_forms.html.haml
.span3
  %ul.nav.nav-list.nav-pills.nav-stacked
    %li.nav-header Ninjitsu
    %li.active= link_to 'Shuriken by Song', '#', class: 'song'
    %li= link_to 'Shuriken by Album', '#', class: 'album'

.span5
  .song-form.wrapper
    = render 'song_creation_services/form'

  .album-form.wrapper
    = render 'album_creation_services/form'

app/views/home/index.html.haml
%h4 Song Ninja

= render 'creation_forms' if user_signed_in?

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Song Ninja", root_path, :class => 'brand'
%ul.nav

  - if user_signed_in?
    %li
      = link_to 'Bands', user_bands_path(current_user)
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'

  - else
    %li
      = link_to 'Login', new_user_session_path
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Song Ninja"
      %meta{:content => content_for?(:description) ? yield(:description) : "Song Ninja", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/song_creation_services/_form.html.haml
= simple_form_for [current_user, @song_service ], html: { class: 'form-inline' } do |f|
  = f.error_notification message: flash[:alert]

  .controls.controls-row
    = f.input_field :band, input_html: { class: 'span3' }, placeholder: 'Band Name'
    = f.input_field :song, input_html: { class: 'span3' }, placeholder: 'Song Name'

  .controls
    = f.submit 'Add Song', class: 'add-song btn btn-success', disable_with: 'Creating...'

app/views/song_creation_services/new.html.haml
= render 'form'

app/views/songs/show.html.haml
= cache @song do
  %h3= best_in_place [:user, @album.band, @album, @song], :title, type: :input

  %blockquote
    %p= best_in_place [:user, @album.band, @album, @song], :lyrics, type: :textarea, display_with:  -> v { v.gsub(/[\r\n]+/, '<br>').html_safe }

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline'
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}